runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: 'root'
  CLOUD_SQL_PASSWORD: 'ybh3DlctYD'
  CLOUD_SQL_DATABASE_NAME: 'pychat'
  CLOUD_SQL_CONNECTION_NAME: 'assignment04-223519:us-east1:chatdb'
